### PR TITLE
Add plugin icon

### LINKED ISSUE #6: Add Plugin Logo
@DelVel Plz add MarkdownDoc Logo.
https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

### PR DESCRIPTION
**Pull request by DelVel**

### CODE REVIEW

**Comment by kdh0324** [comment]
Why every CI is failed?

**Comment by DelVel** [comment]
Look at the log.

**Comment by kdh0324** [comment]
I can't understand the error in Lint. Could you plz let me know about the error, @DelVel?

**Comment by DelVel** [comment]
Removed lint step. It seems the container doesn't support it.

**Comment by DelVel** [comment]
I've turned the auto-merge feature on. Just approve the PR, and let's see what's going on.

**Review by kdh0324 — APPROVED** [review]
Ok, It seems good. If this pr is merged, I'll push this plugin on Intellij.

**Pull request merged**
